iivri/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
] +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

from django.conf.urls import include
from django.views.generic import RedirectView

urlpatterns += [
    url(r'^script/', include('script.urls', namespace = 'script')),
    url(r'^optic/', include('optic.urls', namespace = 'optic' )),
        url(r'^$', RedirectView.as_view(url='/optic/', permanent=True)),
]

optic/urls.py
from django.conf.urls import url
from . import views

from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
          url(r'^$', views.root, name = 'root'),
          url(r'^login/$', login, {'template_name' : 'optic/login.html'}, name = 'login'),
          url(r'^logout/$', logout, {'template_name' : 'optic/logout.html'}, name = 'logout'),
          url(r'^register/$', views.register_view, name = 'register'),
          url(r'^profile/$', views.user_profile, name = 'user_profile'),
          url(r'^profile/edit/$', views.edit_profile, name = 'edit_profile'),
          url(r'^edit-password/$', views.edit_password, name = 'edit_password'),


          url(r'^reset-password/$', password_reset, { 'template_name' : 'optic/reset_password.html', 'post_reset_redirect': 'optic:password_reset_done', 'email_template_name': 'optic/reset_password_email.html'  }, name = 'reset_password'),
          url(r'^reset-password/done/$', password_reset_done,  name = 'password_reset_done'),

          url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, { 'template_name' : 'optic/reset_password_confirm.html', 'post_reset_redirect': 'optic:password_reset_complete'}, name = 'password_reset_confirm'),
          url(r'^reset-password/complete/$', password_reset_complete, {'template_name' :'optic/reset_password_complete.html'},
		name = 'password_reset_complete')

]

script/urls.py
from django.conf.urls import url
from script.views import IdentityList, IdentityCreate, ConditionCreate, DiseaseCreate, TreatmentCreate


urlpatterns = [
   url(r'^patient/$', IdentityList.as_view(), name="script_patient_list"),
   url(r'^patient/create/$', IdentityCreate.as_view(), name="script_patient_create"),
   url(r'^patient/condition/create/$', ConditionCreate.as_view(), name="script_condition_create"),
   url(r'^patient/condition/disease/create/$', DiseaseCreate.as_view(), name="script_disease_create"),
   url(r'^patient/condition/disease/treatment/create/$', TreatmentCreate.as_view(), name="script_treatment_create"),
]

optic/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save



class UserManager(BaseUserManager):

	# Create a model manager for User model with no user name field


	use_in_migrations = True

	def _create_user(self, email, password, **extra_fields):

		# Create and save a User with the given email and password

		if not email:

			raise ValueError('The given email must be set')

		email = self.normalize_email(email)
		user = self.model(email=email, **extra_fields)
		user.set_password(password)
		user.save(using=self._db)
		return user


	def create_user(self, email, password=None, **extra_fields):

		# Create and save a regular User with the given email and password.

		extra_fields.setdefault('is_staff', False)
		extra_fields.setdefault('is_superuser', False)
		return self._create_user(email, password, **extra_fields)

	def create_superuser(self, email, password, **extra_fields):

		# Create and save a SuperUser with the given email and password.

		extra_fields.setdefault('is_staff', True)
		extra_fields.setdefault('is_superuser', True)

		if extra_fields.get('is_staff') is not True:
			raise ValueError('Superuser must have is_staff=True.')

		if extra_fields.get('is_superuser') is not True:
			raise ValueError('Superuser must have is_superuser=True.')

		return self._create_user(email, password, **extra_fields)




class User(AbstractUser):

	username = None
	email = models.EmailField(_('email address'), unique = True)

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []

	objects = UserManager()

optic/forms.py
from django import forms
from django.contrib.auth import get_user_model

from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class Create_user(UserCreationForm):

	email = forms.EmailField(required = True)


	class Meta:

		model = get_user_model()

		fields = (

			'first_name',
			'last_name',
			'email',
			'password1',
			'password2'
		)

		def save(self, commit = True):
			user = super(Create_user, self).save(commit = False)
			user.first_name = self.cleaned_data['first_name']
			user.last_name = self.cleaned_data['last_name']
			user.email = self.cleaned_data['email']

			if commit:

				user.save()

			return user

class Update_user(UserChangeForm):

	class Meta:

		model = get_user_model()

		fields = (

			'email',
			'first_name',
			'last_name',
			'password',


		)

optic/views.py
from django.shortcuts import render, reverse, redirect
from optic.forms import Create_user, Update_user
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm

def root(request):
    return render(request, 'optic/root.html')

def register_view(request):

	if request.method == 'POST':

		form = Create_user(request.POST)

		if form.is_valid():
			form.save()
			return redirect('/optic')

		else:
			return redirect(reverse('optic:logout'))

	else:
		form = Create_user()
		var = {'form' : form}
		return render(request, 'optic/register.html', var)

def user_profile(request):

	var = {'user': request.user}

	return render(request, 'optic/profile.html', var)


def edit_profile(request):

	if request.method == 'POST':

		form = Update_user(request.POST, instance = request.user)


		if form.is_valid():
			form.save()

			return redirect(reverse('optic:user_profile'))

		else:
			return redirect('optic/profile/edit')


	else:

		form = Update_user(instance = request.user)

		var = {'form' : form }

		return render(request, 'optic/edit_profile.html', var)

def edit_password(request):

	if request.method == 'POST':

		form = PasswordChangeForm(data = request.POST, user = request.user)

		if form.is_valid():
			form.save()
			update_session_auth_hash(request, form.user)
			return redirect(reverse('optic:login'))

		else:

			return redirect('/optic/edit-password')
	else:

		form = PasswordChangeForm(user = request.user)

		var = {'form': form}

		# Create change_password instance a place in the the template context
		return render(request, 'optic/edit_password.html', var)

optic/templates/base*template.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load staticfiles %}

    <title>
    {% block title %}
    {% endblock %}
  </title>

    {% block head %}
        <!-- <link rel="stylesheet" type="text/css" href="{% static 'site/normalize.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'site/skeleton.css' %}"> -->
    {% endblock %}


      </head>

  <body>
  <div class  = " container">
              <p class=""><a class = "" href = "{%url 'optic:root'%}" style="font-family:Times New Roman;">iivri</a></p>

{% if user.is_authenticated %}
              <ul class = "">
                <li class=""> <a class="" style = "font-family: Mono" href = "{% url 'script:script_patient_list' %}">  Greetings :  {{ user.first_name}} {{ user.last_name}}</a></li>
                <li class = ""><a class="" href = "{% url 'optic:logout'%}" style="font-family:Times New Roman">Sign Out</a></li>
                <!-- <li class = ""><a class = "" href = "{% url 'optic:user_profile' %}">view Identity </a></li>
                <li class = ""><a class = "" href = "{% url 'optic:edit_profile' %}">edit Identity </a></li> -->
                <!-- <li class = ""><a class = "" href = "{% url 'optic:edit_password'%}">Change password</a> -->
             </ul>
{% else %}
             <ul class = "">
               <li class = ""><a class="" href = "{% url 'optic:login'%}">Sign In</a></li>
                <li class = ""><a class = "" href = "{% url 'optic:register'%}">Sign Up</a></li>
           </ul>

{% endif %}
</div>


<div class="container">
  {% block content %}
  {% endblock %}
</div>



    </body>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>
  </html>