iivri/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
] +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

from django.conf.urls import include
from django.views.generic import RedirectView

urlpatterns += [
    url(r'^script/', include('script.urls', namespace = 'script')),
    url(r'^optic/', include('optic.urls', namespace = 'optic' )),
        url(r'^$', RedirectView.as_view(url='/optic/', permanent=True)),
]

optic/urls.py
from django.conf.urls import url
from . import views

from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
          url(r'^$', views.root, name = 'root'),
          url(r'^login/$', login, {'template_name' : 'optic/login.html'}, name = 'login'),
          url(r'^logout/$', logout, {'template_name' : 'optic/logout.html'}, name = 'logout'),
          url(r'^register/$', views.register_view, name = 'register'),
          url(r'^profile/$', views.user_profile, name = 'user_profile'),
          url(r'^profile/edit/$', views.edit_profile, name = 'edit_profile'),
          url(r'^edit-password/$', views.edit_password, name = 'edit_password'),


          url(r'^reset-password/$', password_reset, { 'template_name' : 'optic/reset_password.html', 'post_reset_redirect': 'optic:password_reset_done', 'email_template_name': 'optic/reset_password_email.html'  }, name = 'reset_password'),
          url(r'^reset-password/done/$', password_reset_done,  name = 'password_reset_done'),

          url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, { 'template_name' : 'optic/reset_password_confirm.html', 'post_reset_redirect': 'optic:password_reset_complete'}, name = 'password_reset_confirm'),
          url(r'^reset-password/complete/$', password_reset_complete, {'template_name' :'optic/reset_password_complete.html'},
		name = 'password_reset_complete')

]

optic/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save



class UserManager(BaseUserManager):

	# Create a model manager for User model with no user name field


	use_in_migrations = True

	def _create_user(self, email, password, **extra_fields):

		# Create and save a User with the given email and password

		if not email:

			raise ValueError('The given email must be set')

		email = self.normalize_email(email)
		user = self.model(email=email, **extra_fields)
		user.set_password(password)
		user.save(using=self._db)
		return user


	def create_user(self, email, password=None, **extra_fields):

		# Create and save a regular User with the given email and password.

		extra_fields.setdefault('is_staff', False)
		extra_fields.setdefault('is_superuser', False)
		return self._create_user(email, password, **extra_fields)

	def create_superuser(self, email, password, **extra_fields):

		# Create and save a SuperUser with the given email and password.

		extra_fields.setdefault('is_staff', True)
		extra_fields.setdefault('is_superuser', True)

		if extra_fields.get('is_staff') is not True:
			raise ValueError('Superuser must have is_staff=True.')

		if extra_fields.get('is_superuser') is not True:
			raise ValueError('Superuser must have is_superuser=True.')

		return self._create_user(email, password, **extra_fields)




class User(AbstractUser):

	username = None
	email = models.EmailField(_('email address'), unique = True)

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []

	objects = UserManager()

optic/forms.py
from django import forms
from django.contrib.auth import get_user_model

from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class Create_user(UserCreationForm):

	email = forms.EmailField(required = True)


	class Meta:

		model = get_user_model()

		fields = (

			'first_name',
			'last_name',
			'email',
			'password1',
			'password2'
		)

		def save(self, commit = True):
			user = super(Create_user, self).save(commit = False)
			user.first_name = self.cleaned_data['first_name']
			user.last_name = self.cleaned_data['last_name']
			user.email = self.cleaned_data['email']

			if commit:

				user.save()

			return user

class Update_user(UserChangeForm):

	class Meta:

		model = get_user_model()

		fields = (

			'email',
			'first_name',
			'last_name',
			'password',


		)

optic/views.py
from django.shortcuts import render, reverse, redirect
from optic.forms import Create_user, Update_user
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm

def root(request):
    return render(request, 'optic/root.html')

def register_view(request):

	if request.method == 'POST':

		form = Create_user(request.POST)

		if form.is_valid():
			form.save()
			return redirect('/optic')

		else:
			return redirect(reverse('optic:logout'))

	else:
		form = Create_user()
		var = {'form' : form}
		return render(request, 'optic/register.html', var)

def user_profile(request):

	var = {'user': request.user}

	return render(request, 'optic/profile.html', var)


def edit_profile(request):

	if request.method == 'POST':

		form = Update_user(request.POST, instance = request.user)


		if form.is_valid():
			form.save()

			return redirect(reverse('optic:user_profile'))

		else:
			return redirect('optic/profile/edit')


	else:

		form = Update_user(instance = request.user)

		var = {'form' : form }

		return render(request, 'optic/edit_profile.html', var)

def edit_password(request):

	if request.method == 'POST':

		form = PasswordChangeForm(data = request.POST, user = request.user)

		if form.is_valid():
			form.save()
			update_session_auth_hash(request, form.user)
			return redirect(reverse('optic:login'))

		else:

			return redirect('/optic/edit-password')
	else:

		form = PasswordChangeForm(user = request.user)

		var = {'form': form}

		# Create change_password instance a place in the the template context
		return render(request, 'optic/edit_password.html', var)

optic/templates/optic/base*template_optic.html
{% extends  parent_template|default:"base*template.html"%}

optic/templates/optic/edit_password.html
{% extends  parent_template|default:"optic/base*template_optic.html"%}


{% block head %}

<title>Change password</title>
{% endblock %}


{% block body %}
<div class = "container" style="margin: 80px;">
<form method="post">
	{% csrf_token %}

	{{ form.as_p }}

	<button class = "btn btn-primary btn-large">
		Create New Password
	</button>
</form>
</div>
{% endblock %}

optic/templates/optic/edit_profile.html
{% extends  parent_template|default:"optic/base*template_optic.html"%}
{% block head %}

<title>edit profile</title>

{% endblock %}


{% block body %}

<div class = "container" style = " font-family: Optima;  margin-top: 80px; ">

<form method = "post">

{% csrf_token %}

		{{ form }}

	<button class = "btn btn-primary btn-large"> Submit Change </button>

</form>


{% endblock %}

optic/templates/optic/login.html
{% extends  parent_template|default:"optic/base*template_optic.html"%}

{% block title %}
    Sign In
{% endblock %}


{% block content %}

          {% if form.errors %}
          <p>Your username and password didn't match. Please try again.</p>
          {% endif %}


          <form method="post" action = "{% url 'optic:login' %}" >
          {% csrf_token %}
          <table>
          <tr>
              <td>{{ form.username.label_tag }}</td>
              <td>{{ form.username }}</td>
          </tr>
          <tr>
              <td>{{ form.password.label_tag }}</td>
              <td>{{ form.password }}</td>
          </tr>
          </table>

          <input  class="btn btn-primary" type="submit" value="login" />

</form>

<a href="{% url 'optic:reset_password' %}">Forgot password?</a>


{% endblock  %}

optic/templates/optic/logout.html
{% extends  parent_template|default:"optic/base*template_optic.html"%}
{% block title %}
      Farwell!
{% endblock %}


{% block content %}
<p class="display-4">Farewell. Next time!</p>

<a href="{% url 'optic:login'%}" class="text-muted">Sign In</a>
{% endblock %}

optic/templates/optic/profile.html
{% extends  parent_template|default:"optic/base*template_optic.html"%}

{% block head %}
    <title>Your Identity</title>
{% endblock %}


{% block sidebar %}
{% endblock %}


{% block body %}

<li class="list-group-item" style = "font-family: Mono">

<p class="h1 text-muted" >{{ user.first_name  }} {{ user.last_name }}</p>

<hr>
<p>Email Address : {{ user.email }}</p>
</li>

{% endblock %}

optic/templates/optic/register.html
{% extends  parent_template|default:"optic/base*template_optic.html"%}
{% block head %}
<title>Sign Up</title>
{% endblock %}


{% block body %}

<form method = "post">

		{% csrf_token %}

<div class = "form-group">

	{{ form.as_ul}}

						<button class = "btn btn-primary btn-large" type="submit">Sign Up</button>
</div>


</form>

{% endblock %}

optic/templates/optic/reset_password.html
{% extends  parent_template|default:"optic/base*template_optic.html"%}

       {% block head %}
    <title>reset your password</title>
    {% endblock %}

    {% block body %}

<div class = "container">
<h1 style="font-family: Mon0">Create  New Password Here</h1>

<p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>

<form method="post">

	{% csrf_token %}

	{{form.as_p}}

	<button class = "btn-large btn btn-primary" type="submit">
		Reset Password
	</button>

</form>
</div>
{% endblock %}
	</body>

</html>

optic/templates/optic/reset_password_complete.html
{% extends  parent_template|default:"optic/base*template_optic.html"%}
{% block head %}
<title>Password reset sent</title>
{% endblock %}



{% block body %}


<div class = "container" style="margin: 80px;">
<h1>Password reset complete</h1>

<a href="{% url 'optic:login' %}" class="btn-large blue">Sign In</a>
</div>
{% endblock %}

optic/templates/optic/reset_password_confirm.html
{% extends  parent_template|default:"optic/base*template_optic.html"%}
{% block head %}
 <title>Reset Your Password</title>
 {% endblock %}


 {% block body %}

<div class = "container" style="margin: 80px;">

<h1>Enter New Password</h1>

<form method="post">

	{% csrf_token %}

	{{form.as_p}}

	<button class = "btn-large btn btn-primary" type="submit">
		Reset Password
	</button>

</form>
</div>
{% endblock %}

optic/templates/optic/reset_password_email.html
{% load i18n %}{% autoescape off %}

2	{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
3
4	{% trans "Please go to the following page and choose a new password:" %}
5	{% block reset_link %}

6	{{ protocol }}://{{ domain }}{% url 'optic:password_reset_confirm' uidb64=uid token=token %}

7	{% endblock %}

8{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}
9
10	{% trans "Thanks for using our site!" %}
11
12	{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
13
14	{% endautoescape %}

optic/templates/optic/root.html
{% extends  parent_template|default:"optic/base*template_optic.html"%}

{% block title %}
 Home
{% endblock %}





{% block content %}
<p>Our mission</p>
<hr>
<p>To serve life itself.</p>
{% endblock %}